import { Alert, Box, Breadcrumbs, Button, Link as MuiLink, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { addWorkspaceNodeAction, generateWorkspaceNodeActions } from '../api/nodeGeneratorApi';
import { LoadingState, SectionCard } from '../components/ui';
import { useNodeGeneratorProject, useSetNodeGeneratorProjectCache } from '../hooks/useNodeGeneratorProject';

export function NodeGeneratorFirstSceneActionsPage() {
  const navigate = useNavigate();
  const { projectId = '', sceneId = '' } = useParams();
  const { data: project, isLoading, isError, error } = useNodeGeneratorProject(projectId);
  const setProjectCache = useSetNodeGeneratorProjectCache();
  const [actionDraft, setActionDraft] = useState('');
  const [autoGenerating, setAutoGenerating] = useState(false);
  const [autoGeneratedOnce, setAutoGeneratedOnce] = useState(false);
  const [localError, setLocalError] = useState<string | null>(null);

  const scene = useMemo(
    () => project?.workspace?.nodes.find((node) => node.id.toUpperCase() === sceneId.toUpperCase()) ?? null,
    [project, sceneId],
  );

  useEffect(() => {
    setAutoGeneratedOnce(false);
    setAutoGenerating(false);
    setLocalError(null);
    setActionDraft('');
  }, [projectId, sceneId]);

  useEffect(() => {
    if (!project || !scene || autoGeneratedOnce || autoGenerating) return;
    let cancelled = false;
    const run = async () => {
      try {
        setLocalError(null);
        setAutoGenerating(true);
        const updated = await generateWorkspaceNodeActions(project.id, scene.id);
        if (cancelled) return;
        setProjectCache(updated);
      } catch (e) {
        if (cancelled) return;
        setLocalError(e instanceof Error ? e.message : 'Failed to generate actions');
      } finally {
        if (cancelled) return;
        setAutoGenerating(false);
        setAutoGeneratedOnce(true);
      }
    };
    void run();
    return () => {
      cancelled = true;
    };
  }, [autoGeneratedOnce, autoGenerating, project, scene, setProjectCache]);

  const handleAddAction = async () => {
    if (!project || !scene || !actionDraft.trim()) return;
    try {
      setLocalError(null);
      const updated = await addWorkspaceNodeAction(project.id, scene.id, actionDraft.trim());
      setProjectCache(updated);
      setActionDraft('');
    } catch (e) {
      setLocalError(e instanceof Error ? e.message : 'Failed to add action');
    }
  };

  if (isLoading) return <LoadingState message="Loading scene..." />;
  if (isError) return <Alert severity="error">{error instanceof Error ? error.message : 'Failed to load scene'}</Alert>;
  if (!project || !scene) return <Alert severity="error">Scene not found</Alert>;

  const generatedActions = (scene.generatedActionsDraft?.length
    ? scene.generatedActionsDraft
    : (scene.actions ?? []).map((action) => action.text).filter((text) => text.trim().length > 0)
  );
  const savedActions = scene.actions ?? [];

  return (
    <Stack spacing={2}>
      {localError ? <Alert severity="error">{localError}</Alert> : null}

      <Breadcrumbs aria-label="breadcrumb">
        <MuiLink component={Link} to="/node-generator" underline="hover" color="inherit">
          All quests
        </MuiLink>
        <MuiLink component={Link} to={`/node-generator/projects/${project.id}`} underline="hover" color="inherit">
          {project.name}
        </MuiLink>
        <Typography color="text.primary">First Scene Actions</Typography>
      </Breadcrumbs>

      <SectionCard title="Scene Description">
        <Typography variant="body2">{scene.stateDescription || scene.actionDescription || 'Description is not set.'}</Typography>
      </SectionCard>

      <SectionCard title="Action Ideas (AI)">
        <Stack spacing={1}>
          {autoGenerating ? <Typography variant="body2" color="text.secondary">Generating actions...</Typography> : null}
          {!autoGenerating && !generatedActions.length ? (
            <Typography variant="body2" color="text.secondary">No generated actions yet.</Typography>
          ) : null}
          {generatedActions.map((item, index) => (
            <Box
              key={`${index}-${item}`}
              role="button"
              tabIndex={0}
              onClick={() => setActionDraft(item)}
              onKeyDown={(event) => {
                if (event.key === 'Enter' || event.key === ' ') setActionDraft(item);
              }}
              sx={{ border: 1, borderColor: 'divider', borderRadius: 1, p: 1, cursor: 'pointer' }}
            >
              <Typography variant="body2">{item}</Typography>
            </Box>
          ))}
        </Stack>
      </SectionCard>

      <SectionCard title="Add Action">
        <Stack spacing={1}>
          <TextField
            label="Action text"
            value={actionDraft}
            onChange={(e) => setActionDraft(e.target.value)}
            fullWidth
            size="small"
          />
          <Button variant="contained" onClick={() => void handleAddAction()} disabled={!actionDraft.trim()}>
            Add Action
          </Button>
        </Stack>
      </SectionCard>

      <SectionCard title="Saved Actions">
        <Stack spacing={0.75}>
          {!savedActions.length ? <Typography variant="body2" color="text.secondary">No saved actions yet.</Typography> : null}
          {savedActions.map((action) => (
            <Typography key={action.id} variant="body2">- {action.text}</Typography>
          ))}
        </Stack>
      </SectionCard>

      <Button
        variant="contained"
        onClick={() => navigate(`/node-generator/projects/${project.id}/scenes/${encodeURIComponent(scene.id)}`)}
      >
        Done
      </Button>
    </Stack>
  );
}

